builders:
  mirror:
    target: ":mirror_builder"
    import: "package:mirror_builder/mirror_builder.dart"
    builder_factories: [ "mirrorBuilder" ]
    build_extensions: { ".dart": [ ".mirror.dart" ] }
    auto_apply: root_package
    build_to: source
    defaults:
      generate_for:
        include:
          - benchmark/**.dart
          - bin/**.dart
          - example/**.dart
          - lib/main.dart
          - test/**.dart
          - tool/**.dart
          - web/**.dart